services:
  marzban-node:
    image: gozargah/marzban-node:latest
    restart: always
    network_mode: host
    environment:
      SSL_CLIENT_CERT_FILE: "/var/lib/marzban-node/cert.pem"
      SERVICE_PORT: "62050"
      XRAY_API_PORT: "62051"
      SERVICE_PROTOCOL: "rest"
      XRAY_EXECUTABLE_PATH: "/var/lib/marzban-node/xray-core/xray"
      XRAY_ASSETS_PATH: "/var/lib/marzban-node/xray-core"
    volumes:
      - /var/lib/marzban-node:/var/lib/marzban
      - /var/lib/marzban-node:/var/lib/marzban-node

  nginx:
    image: nginx:latest
    restart: always
    network_mode: host
    volumes:
      - ./nginx.conf:/etc/nginx/nginx.conf
      - ./nginx-log:/var/log/nginx
      - /etc/letsencrypt:/etc/letsencrypt
    depends_on:
      - marzban-node
